### ISSUE TITLE
Masking of dresses

### ISSUE THREAD

**Issue by cuuupid** [yisol/IDM-VTON#12]
Hey @yisol, this is an awesome model!

I'm trying to figure out why this is performing strangely on dresses. Specifically it seems to be just filling in the mask of the body/currently worn clothing with the dress, instead of inpainting the correct length/shape of the dress.

Here are some examples with a short floral sundress:

https://replicate.com/p/pkzppt6wphrgm0ceswqb8dj8dr
https://replicate.com/p/pgr284mnm9rgg0ceswqb8pesm4
https://replicate.com/p/yngjhan5thrgm0ceswpr1b54g0
https://replicate.com/p/twkg8appqnrgg0ceswp8a5ws6r
https://replicate.com/p/jdpt1zm11xrgm0ceswpb4fqgn0

Any recommendations to fix this?

**Comment by yisol** [comment]
Hello, I think the links you provided are broken, but I guess that's because the model was trained with upper garment images only.
We released one more model trained on dresscode dataset (including upper garment, lower garment and dresses).
You can try dress images with this model.

**Comment by cuuupid** [comment]
Apologies, have fixed the links above. I believe they use the dresscode model, they are based on the huggingface space. They have visual fidelity but are not accurate to the garment.

**Comment by yisol** [comment]
The model on huggingface space demo is trained with upper garments only.
We released a script for inference for dresscode dataset on github.
We will add the DressCode model on huggingface soon.
