### ISSUE TITLE
Minimum GPU memory requirements (inference)

### ISSUE THREAD

**Issue by tonySSAI** [yisol/IDM-VTON#15]
Hi. 
I was running the inference code on a 12GB 3060GPU, but I always ran into CUDA_OUT_OF_MEMORY error no matter what I do. Following is my inference command.
```
accelerate launch inference.py --width 384 --height 512 --num_inference_steps 30 --output_dir "result" --unpaired \
--data_dir datasets --test_batch_size 1 --guidance_scale 2.0 --mixed_precision bf16 --enable_xformers_memory_efficient_attention
```

I would like to know the minimum requirements for GPU configuration for running training and inference code. Furthermore, is there any other way to decrease the memory requirements besides enabling Mixed Precision, decreasing resolution and using xformers?

**Comment by GeneralWhite** [comment]
I'm running the inference code on a 24GB 4090GPU and I'm also getting the CUDA_OUT_OF_MEMORY error

**Comment by yisol** [comment]
Hello, we used mixed precision(fp16) for inference. It should be worked with VRAM < 18GB on fp16.
You can also try more optimizations like offloading @vcadillog mentioned for further reducing VRAM.
