### ISSUE TITLE
No module named 'torchvision.transforms.functional_tensor

### ISSUE THREAD

**Issue by merolaika** [yisol/IDM-VTON#25]
Hello i get this error, can any 1 have  idea? thanks.
`
C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\Scripts\activate C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env && python app.py
C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_p
Microsoft Windows [Version 10.0.22631.3447]
(c) Microsoft Corporation. Tüm hakları saklıdır.

C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\Scripts\activate C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env && python app.py
C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
The config attributes {'decay': 0.9999, 'inv_gamma': 1.0, 'min_decay': 0.0, 'optimization_step': 37000, 'power': 0.6666666666666666, 'update_after_step': 0, 'use_ema_warmup': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel: 
 ['add_embedding.linear_1.bias, add_embedding.linear_1.weight, add_embedding.linear_2.bias, add_embedding.linear_2.weight']
Traceback (most recent call last):
  File "C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\app.py", line 102, in <module>
    openpose_model = OpenPose(0)
  File "C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\preprocess\openpose\run_openpose.py", line 33, in __init__
    self.preprocessor = OpenposeDetector()
  File "C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\preprocess\openpose\annotator\openpose\__init__.py", line 52, in __init__
    from basicsr.utils.download_util import load_file_from_url
  File "C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "C:\YapayZeka\pinokio\bin\miniconda\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app\env\lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

(env) (base) C:\YapayZeka\pinokio\api\ust-degis-idm-vton.git\app>
[Start proxy] Local Sharing {{input.event[0]}}
Proxy Started {"target":"{{input.event[0]}}","proxy":"http://192.168.56.1:42421"}
`

**Comment by yisol** [comment]
Hello, we tested with torchvision=0.15.2=py310_cu118 as specified on environment.yaml file.
You can check your torchvision library version.
