### ISSUE TITLE
About agnostic-mask

### ISSUE THREAD

**Issue by kentonson** [yisol/IDM-VTON#32]
Great job. I tried to execute the inference code, but found that there was no agnostic-mask data. Do you have plans to release this data?

**Comment by George0726** [comment]
Hi there, I confront the same issue. How did you solve it out?

**Comment by kentonson** [comment]
@George0726 Well, I probably forgot where I got this data, I can't find the address of the source project, but I uploaded a copy on my google drive, and you can download it from [here](https://drive.google.com/file/d/188Be_wcyr5CEBrZSrmBx_hQYt2KXs3C1/view?usp=sharing), enjoy!
