### ISSUE TITLE
Few questions for the paper

### ISSUE THREAD

**Issue by ifeherva** [yisol/IDM-VTON#5]
- Did you drop conditions during training? If yes, what rate?

- In the appendix you list only the IP adapter and the garment unet's output as condition, did you drop the text prompt, the time_ids and all that other jazz SDXL needs when you compute CFG?

- did you use the IPAdapter in diffusers vanilla or needed some modifications?

Thank you

**Comment by yisol** [comment]
Hello, 
1. We found that inference with cfg is effective even without condition droping during training, so we didn't drop conditions during training.
2. We also dropped other conditions like add_text_embeds, add_time_ids that SDXL requires
3. We used vanilla IP-Adapter in IP-Adapter github repo

**Comment by ifeherva** [comment]
Appreciate the responses!
