### ISSUE TITLE
How can I integrate my own masking models? YoloV8

### ISSUE THREAD

**Issue by dancingninjaaaaa** [yisol/IDM-VTON#58]
Hi @yisol, I want to change your pipeline a bit, I want to integrate my own, masking models. I want to integrate yolov8 lower body, and full body inside it. Can you someone please provide some guidance.

**Comment by Manish989927** [comment]
I think use this 
https://colab.research.google.com/drive/1aMbKHn5dVXwhnTtC9NIWm3KDG7bzNjrF?usp=sharing
that help you to understand

**Comment by dancingninjaaaaa** [comment]
Hi, not this, I already have trained yolov8, I just want to integrate them inside IDM-VTON.

**Comment by dancingninjaaaaa** [comment]
@yisol From where you are importing openposedetector? Can't find it...
