### ISSUE TITLE
Train and inference code

### ISSUE THREAD

**Issue by cardosofelipe** [yisol/IDM-VTON#6]
Hi, very impressive work, your demo looks amazing. Do you have any plan for releasing train and inference code along with the base architecture?

**Comment by yisol** [comment]
Hello, we just released inference code, and will release training code as well.

**Comment by cardosofelipe** [comment]
> Hello, we just released inference code, and will release training code as well.


Hi, I know you already closed the issue, sorry for resuming it. But I wanted to ask: do you have an ETA on the releasing of the training code?
