### ISSUE TITLE
The config attributes {'decay': 0.9999, 'inv_gamma': 1.0, 'min_decay': 0.0, 'optimization_step': 37000, 'power': 0.6666666666666666, 'update_after_step': 0, 'use_ema_warmup': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file. Killed

### ISSUE THREAD

**Issue by DeepAlgoExpert** [yisol/IDM-VTON#64]
Thanks for your great work.
I tried to run gradio demo on ubuntu with cuda 11.8 but got error.
![git-error](https://github.com/yisol/IDM-VTON/assets/153261668/9d971b99-7861-49c7-ba4e-10297ee2f78e)
Please help me!
Thanks.

**Comment by FurkanGozukara** [comment]
killed means not enough RAM usually

**Comment by FurkanGozukara** [comment]
well we have even 8 GB VRAM working version

even if you dont have sufficient RAM it should work with virtual RAM

for Windows : https://youtu.be/m4pcIeAVQD0
for linux / ubuntu : https://youtu.be/LeHfgq_lAXU

**Comment by hetsalk** [comment]
I get same error while tring to run command 

python gradio_demo/app.py

But i have 16 GB RAM and every time when i run this command it acquirer all 16 GB ram and it caused my pc was hanged. 
So please provide solution for that.

**Comment by jeffryWillam** [comment]
> I get same error while tring to run command
> 
> python gradio_demo/app.py
> 
> But i have 16 GB RAM and every time when i run this command it acquirer all 16 GB ram and it caused my pc was hanged. So please provide solution for that.

the same. Have u solved the problem?

**Comment by longding717** [comment]
I have 64g of RAM and 24g of GPU memory, but the same error message appears. It's puzzling.

**Comment by Utkarsh13tiwari** [comment]
Getting the same issue.

Laptop config= 8 cores CPU, 1660 4gm RAM GeforceGTX GPU, 16 GB RAM and 512GB SSD.

Any possible fix to the issue please help me out.

**Comment by Utkarsh13tiwari** [comment]
@SailochanaR  
error:

The config attributes {'decay': 0.9999, 'inv_gamma': 1.0, 'min_decay': 0.0, 'optimization_step': 37000, 'power': 0.6666666666666666, 'update_after_step': 0, 'use_ema_warmup': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file. Killed

-------------------------------------------------------------------------------------------------------------------
there is no error, but seems to some problem with memory according to the previous comments/suggestions. Look the above warning

**Comment by Utkarsh13tiwari** [comment]
@SailochanaR  So whats the possible fix? should i use AWS ec2 instance for running the API?

How did you overcome the error?

**Comment by shahzain110** [comment]
Previously i was running on colab CPU, then shifted to L4 GPU, this worked for me.
