### ISSUE TITLE
Inference for Dresscode

### ISSUE THREAD

**Issue by mianemad** [yisol/IDM-VTON#7]
Will you release the inference code for the Dresscode dataset? If yes, when would that be?

**Comment by yisol** [comment]
Hello,
We will upload a inference script for DressCode dataset within a week

**Comment by mianemad** [comment]
> Hello, We will upload a inference script for DressCode dataset within a week

Thank you for the quick reply, could also know what is the inference time/execution time of the model?

**Comment by yisol** [comment]
It takes about 7 seconds for a single image on a single A100 GPU.
